name: geodos
description: Portal GEODOS
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  uuid: ^4.1.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/proyectos_por_municipio_cat_isla_v3_jittered.json